### ISSUE TITLE
'Invalid token' error with default example.

### ISSUE THREAD

**Issue by joshuaiz** [ethomson/send-tweet-action#9]
Trying to send a tweet on push using the default example:

```
name: Send a Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Test post from GitHub Actions."
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
```
and getting the following error:

```
Run ethomson/send-tweet-action@v1

/home/runner/work/_actions/ethomson/send-tweet-action/v1/dist/index.js:4841
                    throw error;
                    ^
[ { code: 89, message: 'Invalid or expired token.' } ]
```
My keys are in `secrets` and the app has Read + Write permissions on Twitter. 

I tried:
- regenerating new keys
- creating a new project with new keys
- changing permissions from 'Read, Write + Direct Message' to just 'Read + Write' *and* generated new keys

^^ none of these are working.

Any idea why this wouldn't work and why I would be getting this error with new/regenerated keys?
